[versions]
kotlin-multiplatform = "1.9.0"
ktlint = "0.50.0"

[libraries]
darkrockstudios-mpfilepicker = { module = "com.darkrockstudios:mpfilepicker", version = "1.2.0" }
google-gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
materialkolor = { module = "com.materialkolor:material-kolor", version = "1.2.0" }
dansoftowner-jthemedetecor = { module = "com.github.Dansoftowner:jSystemThemeDetector", version = "3.8" }

[plugins]
jetbrains-compose = { id = "org.jetbrains.compose", version = "1.4.3" }
jlleitschuh-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.5.0" }
conveyor = { id = "dev.hydraulic.conveyor", version = "1.6" }
