# https://github.com/mooltiverse/nyx-github-action
name: Nyx Release
on:
  push:
    branches: [ "main" ]
    
jobs:
  nyx:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      id-token: read
      packages: write
      pages: write
      statuses: read
  
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Nyx publish
      id: nyx
      uses: mooltiverse/nyx-github-action@main
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NYX_VERBOSITY: 'INFO'
      with:
        command: 'publish'
